# Nicolle Ayon C.
# nayoncam
# This makefile with macros is for fileReverse.c
# Makefile

FLAGS   = -std=c99 -Wall
SOURCES = fileReverse.c
OBJECTS = fileReverse.o
EXEBIN  = fileReverse

all: $(EXEBIN)

$(EXEBIN) : $(OBJECTS)
	gcc -o $(EXEBIN) $(OBJECTS)

$(OBJECTS) : $(SOURCES)
	gcc -c $(FLAGS) $(SOURCES)

clean :
	rm -f $(EXEBIN) $(OBJECTS)